//
// UpdateNotificationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateNotificationRequest: Codable, JSONEncodable, Hashable {

    public var read: Bool

    public init(read: Bool) {
        self.read = read
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case read
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(read, forKey: .read)
    }
}

