//
// UptimeItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** UptimeItem represents a monitoring period&#39;s uptime statistics for a website */
public struct UptimeItem: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var accountId: Int
    public var date: String
    public var failedRequests: String
    public var monitoringProfile: String
    public var p95: String
    public var successfulRequests: String
    public var totalRequests: String

    public init(id: Int, accountId: Int, date: String, failedRequests: String, monitoringProfile: String, p95: String, successfulRequests: String, totalRequests: String) {
        self.id = id
        self.accountId = accountId
        self.date = date
        self.failedRequests = failedRequests
        self.monitoringProfile = monitoringProfile
        self.p95 = p95
        self.successfulRequests = successfulRequests
        self.totalRequests = totalRequests
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case accountId
        case date
        case failedRequests
        case monitoringProfile
        case p95
        case successfulRequests
        case totalRequests
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(accountId, forKey: .accountId)
        try container.encode(date, forKey: .date)
        try container.encode(failedRequests, forKey: .failedRequests)
        try container.encode(monitoringProfile, forKey: .monitoringProfile)
        try container.encode(p95, forKey: .p95)
        try container.encode(successfulRequests, forKey: .successfulRequests)
        try container.encode(totalRequests, forKey: .totalRequests)
    }
}

