//
// BulkImportAccepted.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Acknowledgement that a bulk import job has been queued */
public struct BulkImportAccepted: Codable, JSONEncodable, Hashable {

    public var jobId: String
    public var total: Int
    public var statusUrl: String

    public init(jobId: String, total: Int, statusUrl: String) {
        self.jobId = jobId
        self.total = total
        self.statusUrl = statusUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jobId
        case total
        case statusUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(jobId, forKey: .jobId)
        try container.encode(total, forKey: .total)
        try container.encode(statusUrl, forKey: .statusUrl)
    }
}

