//
// BulkImportResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Per-row outcome of a bulk monitoring-profile import */
public struct BulkImportResult: Codable, JSONEncodable, Hashable {

    public var total: Int
    public var created: Int
    public var skipped: [BulkImportResultSkippedInner]
    public var failed: [BulkImportResultFailedInner]

    public init(total: Int, created: Int, skipped: [BulkImportResultSkippedInner], failed: [BulkImportResultFailedInner]) {
        self.total = total
        self.created = created
        self.skipped = skipped
        self.failed = failed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case created
        case skipped
        case failed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(total, forKey: .total)
        try container.encode(created, forKey: .created)
        try container.encode(skipped, forKey: .skipped)
        try container.encode(failed, forKey: .failed)
    }
}

