//
// BulkImportStatusProgress.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BulkImportStatusProgress: Codable, JSONEncodable, Hashable {

    public var done: Int
    public var total: Int

    public init(done: Int, total: Int) {
        self.done = done
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case done
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(done, forKey: .done)
        try container.encode(total, forKey: .total)
    }
}

