//
// BulkImportStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Status and results of a bulk monitoring-profile import job */
public struct BulkImportStatus: Codable, JSONEncodable, Hashable {

    public enum State: String, Codable, CaseIterable {
        case waiting = "waiting"
        case active = "active"
        case completed = "completed"
        case failed = "failed"
    }
    public var jobId: String
    public var state: State
    public var progress: BulkImportStatusProgress
    public var result: BulkImportResult?

    public init(jobId: String, state: State, progress: BulkImportStatusProgress, result: BulkImportResult?) {
        self.jobId = jobId
        self.state = state
        self.progress = progress
        self.result = result
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jobId
        case state
        case progress
        case result
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(jobId, forKey: .jobId)
        try container.encode(state, forKey: .state)
        try container.encode(progress, forKey: .progress)
        try container.encode(result, forKey: .result)
    }
}

