//
// BulkImportResultFailedInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BulkImportResultFailedInner: Codable, JSONEncodable, Hashable {

    public var url: String
    public var error: String

    public init(url: String, error: String) {
        self.url = url
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encode(error, forKey: .error)
    }
}

