//
// BulkImportResultSkippedInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BulkImportResultSkippedInner: Codable, JSONEncodable, Hashable {

    public var url: String
    public var reason: String

    public init(url: String, reason: String) {
        self.url = url
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encode(reason, forKey: .reason)
    }
}

