//
// GetMonitoringProfileRegistrarData200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GetMonitoringProfileRegistrarData200Response: Codable, JSONEncodable, Hashable {
    case typeRegistrarData(RegistrarData)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeRegistrarData(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(RegistrarData.self) {
            self = .typeRegistrarData(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of GetMonitoringProfileRegistrarData200Response"))
        }
    }
}

