//
// PlomerNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** PlomerNotification represents a system message or alert for a user */
public struct PlomerNotification: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case domainExpiry = "DOMAIN_EXPIRY"
        case sslExpiry = "SSL_EXPIRY"
        case websiteDown = "WEBSITE_DOWN"
        case contentChange = "CONTENT_CHANGE"
        case system = "SYSTEM"
    }
    public var id: Int
    public var accountId: Int
    public var text: String
    public var type: ModelType
    public var read: Bool = false
    public var createdAt: String
    public var updatedAt: String

    public init(id: Int, accountId: Int, text: String, type: ModelType, read: Bool = false, createdAt: String, updatedAt: String) {
        self.id = id
        self.accountId = accountId
        self.text = text
        self.type = type
        self.read = read
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case accountId
        case text
        case type
        case read
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(accountId, forKey: .accountId)
        try container.encode(text, forKey: .text)
        try container.encode(type, forKey: .type)
        try container.encode(read, forKey: .read)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}

