//
// Product.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The product to purchase */
public enum Product: String, Codable, CaseIterable {
    case weekly = "PLOMER_WEEKLY"
    case monthly = "PLOMER_MONTHLY"
    case yearly = "PLOMER_YEARLY"
}
