//
// UptimeItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** UptimeItem represents a monitoring period&#39;s uptime statistics for a website */
public struct UptimeItem: Codable, JSONEncodable, Hashable {

    public var accountId: Int
    public var date: String
    public var failedRequests: Int
    public var monitoringProfileId: Int
    public var p95: Double
    public var successful: Int
    public var total: Int

    public init(accountId: Int, date: String, failedRequests: Int, monitoringProfileId: Int, p95: Double, successful: Int, total: Int) {
        self.accountId = accountId
        self.date = date
        self.failedRequests = failedRequests
        self.monitoringProfileId = monitoringProfileId
        self.p95 = p95
        self.successful = successful
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId
        case date
        case failedRequests
        case monitoringProfileId
        case p95
        case successful
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accountId, forKey: .accountId)
        try container.encode(date, forKey: .date)
        try container.encode(failedRequests, forKey: .failedRequests)
        try container.encode(monitoringProfileId, forKey: .monitoringProfileId)
        try container.encode(p95, forKey: .p95)
        try container.encode(successful, forKey: .successful)
        try container.encode(total, forKey: .total)
    }
}

