//
// CreateApiKey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Input schema for creating a new API key */
public struct CreateApiKey: Codable, JSONEncodable, Hashable {

    public var name: String
    public var expiresAt: Date?

    public init(name: String, expiresAt: Date? = nil) {
        self.name = name
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case expiresAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
    }
}

