//
// DowntimeStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Downtime stats */
public struct DowntimeStats: Codable, JSONEncodable, Hashable {

    public var totalIncidents: Double
    public var unresolvedIncidents: Double
    public var averageDowntimeMinutes: Double
    public var totalDowntimeMinutes: Double
    public var uptimePercentage: Double

    public init(totalIncidents: Double, unresolvedIncidents: Double, averageDowntimeMinutes: Double, totalDowntimeMinutes: Double, uptimePercentage: Double) {
        self.totalIncidents = totalIncidents
        self.unresolvedIncidents = unresolvedIncidents
        self.averageDowntimeMinutes = averageDowntimeMinutes
        self.totalDowntimeMinutes = totalDowntimeMinutes
        self.uptimePercentage = uptimePercentage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalIncidents
        case unresolvedIncidents
        case averageDowntimeMinutes
        case totalDowntimeMinutes
        case uptimePercentage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(totalIncidents, forKey: .totalIncidents)
        try container.encode(unresolvedIncidents, forKey: .unresolvedIncidents)
        try container.encode(averageDowntimeMinutes, forKey: .averageDowntimeMinutes)
        try container.encode(totalDowntimeMinutes, forKey: .totalDowntimeMinutes)
        try container.encode(uptimePercentage, forKey: .uptimePercentage)
    }
}

