//
// GetDowntimeIncidents200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetDowntimeIncidents200Response: Codable, JSONEncodable, Hashable {

    public var incidents: [DowntimeIncident]
    public var totalCount: Double

    public init(incidents: [DowntimeIncident], totalCount: Double) {
        self.incidents = incidents
        self.totalCount = totalCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case incidents
        case totalCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(incidents, forKey: .incidents)
        try container.encode(totalCount, forKey: .totalCount)
    }
}

