//
// GetNotifications200ResponsePagination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetNotifications200ResponsePagination: Codable, JSONEncodable, Hashable {

    public var page: Double
    public var totalPages: Double
    public var totalItems: Double
    public var hasMore: Bool

    public init(page: Double, totalPages: Double, totalItems: Double, hasMore: Bool) {
        self.page = page
        self.totalPages = totalPages
        self.totalItems = totalItems
        self.hasMore = hasMore
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case page
        case totalPages
        case totalItems
        case hasMore
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(page, forKey: .page)
        try container.encode(totalPages, forKey: .totalPages)
        try container.encode(totalItems, forKey: .totalItems)
        try container.encode(hasMore, forKey: .hasMore)
    }
}

