//
// ResponseTimes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** ResponseTimes represents a response time for a monitoring profile */
public struct ResponseTimes: Codable, JSONEncodable, Hashable {

    public var time: String
    public var monitoringProfileId: Int
    public var accountId: Int
    public var value: Double

    public init(time: String, monitoringProfileId: Int, accountId: Int, value: Double) {
        self.time = time
        self.monitoringProfileId = monitoringProfileId
        self.accountId = accountId
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case monitoringProfileId
        case accountId
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(time, forKey: .time)
        try container.encode(monitoringProfileId, forKey: .monitoringProfileId)
        try container.encode(accountId, forKey: .accountId)
        try container.encode(value, forKey: .value)
    }
}

