//
// UpdateAccountRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateAccountRequest: Codable, JSONEncodable, Hashable {

    public var hasSubscription: Bool?
    public var enablePushNotifications: Bool?

    public init(hasSubscription: Bool? = nil, enablePushNotifications: Bool? = nil) {
        self.hasSubscription = hasSubscription
        self.enablePushNotifications = enablePushNotifications
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hasSubscription
        case enablePushNotifications
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(hasSubscription, forKey: .hasSubscription)
        try container.encodeIfPresent(enablePushNotifications, forKey: .enablePushNotifications)
    }
}

